title: Tufts Blockchain
description: All members of the Tufts community interested in blockchain, decentralization, crypto -currency -economics, etc., from all skill levels and backgrounds are welcome.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
